### ISSUE TITLE
"Credential", "secret", "id", "expiry" documentation confusion

### ISSUE THREAD

**Issue by jidanni** [dlenski/python-vipaccess#44] opened 2020-07-02 15:22 UTC
In README.md it is not very clear about what will be **expiring**,
```
Credential created successfully:
	otpauth://totp/VIP%20Access:VSST12345678?secret=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA&issuer=Symantec&algorithm=SHA1&digits=6
This credential expires on this date: 2019-01-15T12:00:00.000Z
```
It is not clear if the _credential_ refers to the whole line, or just part of it.

`You will need the ID to register this credential: VSST12345678`

Maybe this is trying to say instead

`You will need the ID: VSST12345678 to register this credential`

Also
```
Here is the format of the .vipaccess...

version 1
secret AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
id VSST12345678
expiry 2019-01-15T12:00:00.000Z
```
So maybe _secret_ = _credential_, and _id_ is what _expiry_ is referring to.

But above, it says "This _credential_ expires on this date...", so maybe the _secret_ is what is expiring.

But maybe _credential_ refers to _secret_ + _id_. And _id_ is what is expiring, so that is why _credential_ is thus also expiring.

Anyway there are each item seems to have several names making the article quite confusing.

(I am assuming that we have two years to call our bank, etc. and tell them the SYMC etc. number, and then can use the _secret_ happily ever after. Or maybe indeed they both die after two years :-( )

**Comment by dlenski** [comment] 2020-07-08 00:09
Duplicate of #11.

[The meaning of "expiration" is dependent on how Symantec implements the validation API, and perhaps how the companies that use Symantec VIP Access use/follow that API. See [this comment](https://github.com/dlenski/python-vipaccess/issues/11#issuecomment-372829370).

> (I am assuming that we have two years to call our bank, etc. and tell them the SYMC etc. number, and then can use the secret happily ever after. Or maybe indeed they both die after two years :-( )

Yes. The intention is that the company using VIP Access validation will _cease to accept_ codes generated with this secret+id at the expiration timestamp.

**Closed** 2020-07-08 00:09 UTC
Labels: documentation, duplicate
